### PR TITLE
feat: Add support for RowVersion columns

### PR DESCRIPTION
**Pull request by nedyalkonikolov**

### CODE REVIEW

**Comment by kalinkrustev** [comment]
please fix this in the .coffee sources and transpile to .js

**Comment by nedyalkonikolov** [comment]
Should I update to the latest CoffeeScript version (1.12.5) or use the version used to compile previous JavaScript code (1.10.0)? Changing the version will result in some minor changes due to different CoffeeScript compilation.

**Comment by kalinkrustev** [comment]
I can't comment without seeing the changes. Is there any benefit of updating?

**Comment by kalinkrustev** [comment]
Do we still need anything from these changes?

**Pull request closed without merging**
